/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRetrieverRouteImport } from './routes/_authenticated/retriever'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated/prompts'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated/policies'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedObservabilityRouteImport } from './routes/_authenticated/observability'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedMcpRouteImport } from './routes/_authenticated/mcp'
import { Route as AuthenticatedHarnessRouteImport } from './routes/_authenticated/harness'
import { Route as AuthenticatedExperimentsRouteImport } from './routes/_authenticated/experiments'
import { Route as AuthenticatedEvaluationsRouteImport } from './routes/_authenticated/evaluations'
import { Route as AuthenticatedDeploymentsRouteImport } from './routes/_authenticated/deployments'
import { Route as AuthenticatedDatasetsRouteImport } from './routes/_authenticated/datasets'
import { Route as AuthenticatedContextRouteImport } from './routes/_authenticated/context'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/_authenticated/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRetrieverRoute = AuthenticatedRetrieverRouteImport.update({
  id: '/_authenticated/retriever',
  path: '/retriever',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/_authenticated/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/_authenticated/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/_authenticated/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/_authenticated/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/_authenticated/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedObservabilityRoute =
  AuthenticatedObservabilityRouteImport.update({
    id: '/_authenticated/observability',
    path: '/observability',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/_authenticated/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/_authenticated/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMcpRoute = AuthenticatedMcpRouteImport.update({
  id: '/_authenticated/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHarnessRoute = AuthenticatedHarnessRouteImport.update({
  id: '/_authenticated/harness',
  path: '/harness',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExperimentsRoute =
  AuthenticatedExperimentsRouteImport.update({
    id: '/_authenticated/experiments',
    path: '/experiments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEvaluationsRoute =
  AuthenticatedEvaluationsRouteImport.update({
    id: '/_authenticated/evaluations',
    path: '/evaluations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDeploymentsRoute =
  AuthenticatedDeploymentsRouteImport.update({
    id: '/_authenticated/deployments',
    path: '/deployments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDatasetsRoute = AuthenticatedDatasetsRouteImport.update({
  id: '/_authenticated/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContextRoute = AuthenticatedContextRouteImport.update({
  id: '/_authenticated/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/_authenticated/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/context': typeof AuthenticatedContextRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/deployments': typeof AuthenticatedDeploymentsRoute
  '/evaluations': typeof AuthenticatedEvaluationsRoute
  '/experiments': typeof AuthenticatedExperimentsRoute
  '/harness': typeof AuthenticatedHarnessRoute
  '/mcp': typeof AuthenticatedMcpRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/models': typeof AuthenticatedModelsRoute
  '/observability': typeof AuthenticatedObservabilityRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/research': typeof AuthenticatedResearchRoute
  '/retriever': typeof AuthenticatedRetrieverRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/context': typeof AuthenticatedContextRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/deployments': typeof AuthenticatedDeploymentsRoute
  '/evaluations': typeof AuthenticatedEvaluationsRoute
  '/experiments': typeof AuthenticatedExperimentsRoute
  '/harness': typeof AuthenticatedHarnessRoute
  '/mcp': typeof AuthenticatedMcpRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/models': typeof AuthenticatedModelsRoute
  '/observability': typeof AuthenticatedObservabilityRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/research': typeof AuthenticatedResearchRoute
  '/retriever': typeof AuthenticatedRetrieverRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/context': typeof AuthenticatedContextRoute
  '/_authenticated/datasets': typeof AuthenticatedDatasetsRoute
  '/_authenticated/deployments': typeof AuthenticatedDeploymentsRoute
  '/_authenticated/evaluations': typeof AuthenticatedEvaluationsRoute
  '/_authenticated/experiments': typeof AuthenticatedExperimentsRoute
  '/_authenticated/harness': typeof AuthenticatedHarnessRoute
  '/_authenticated/mcp': typeof AuthenticatedMcpRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/observability': typeof AuthenticatedObservabilityRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/policies': typeof AuthenticatedPoliciesRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/retriever': typeof AuthenticatedRetrieverRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/context'
    | '/datasets'
    | '/deployments'
    | '/evaluations'
    | '/experiments'
    | '/harness'
    | '/mcp'
    | '/memory'
    | '/models'
    | '/observability'
    | '/planner'
    | '/policies'
    | '/projects'
    | '/prompts'
    | '/research'
    | '/retriever'
    | '/settings'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/context'
    | '/datasets'
    | '/deployments'
    | '/evaluations'
    | '/experiments'
    | '/harness'
    | '/mcp'
    | '/memory'
    | '/models'
    | '/observability'
    | '/planner'
    | '/policies'
    | '/projects'
    | '/prompts'
    | '/research'
    | '/retriever'
    | '/settings'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/agents'
    | '/_authenticated/context'
    | '/_authenticated/datasets'
    | '/_authenticated/deployments'
    | '/_authenticated/evaluations'
    | '/_authenticated/experiments'
    | '/_authenticated/harness'
    | '/_authenticated/mcp'
    | '/_authenticated/memory'
    | '/_authenticated/models'
    | '/_authenticated/observability'
    | '/_authenticated/planner'
    | '/_authenticated/policies'
    | '/_authenticated/projects'
    | '/_authenticated/prompts'
    | '/_authenticated/research'
    | '/_authenticated/retriever'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedContextRoute: typeof AuthenticatedContextRoute
  AuthenticatedDatasetsRoute: typeof AuthenticatedDatasetsRoute
  AuthenticatedDeploymentsRoute: typeof AuthenticatedDeploymentsRoute
  AuthenticatedEvaluationsRoute: typeof AuthenticatedEvaluationsRoute
  AuthenticatedExperimentsRoute: typeof AuthenticatedExperimentsRoute
  AuthenticatedHarnessRoute: typeof AuthenticatedHarnessRoute
  AuthenticatedMcpRoute: typeof AuthenticatedMcpRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedObservabilityRoute: typeof AuthenticatedObservabilityRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedRetrieverRoute: typeof AuthenticatedRetrieverRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/retriever': {
      id: '/_authenticated/retriever'
      path: '/retriever'
      fullPath: '/retriever'
      preLoaderRoute: typeof AuthenticatedRetrieverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/observability': {
      id: '/_authenticated/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof AuthenticatedObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mcp': {
      id: '/_authenticated/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof AuthenticatedMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/harness': {
      id: '/_authenticated/harness'
      path: '/harness'
      fullPath: '/harness'
      preLoaderRoute: typeof AuthenticatedHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/experiments': {
      id: '/_authenticated/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof AuthenticatedExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/evaluations': {
      id: '/_authenticated/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof AuthenticatedEvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/deployments': {
      id: '/_authenticated/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof AuthenticatedDeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/datasets': {
      id: '/_authenticated/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AuthenticatedDatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/context': {
      id: '/_authenticated/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof AuthenticatedContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedContextRoute: AuthenticatedContextRoute,
  AuthenticatedDatasetsRoute: AuthenticatedDatasetsRoute,
  AuthenticatedDeploymentsRoute: AuthenticatedDeploymentsRoute,
  AuthenticatedEvaluationsRoute: AuthenticatedEvaluationsRoute,
  AuthenticatedExperimentsRoute: AuthenticatedExperimentsRoute,
  AuthenticatedHarnessRoute: AuthenticatedHarnessRoute,
  AuthenticatedMcpRoute: AuthenticatedMcpRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedObservabilityRoute: AuthenticatedObservabilityRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedRetrieverRoute: AuthenticatedRetrieverRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
