/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ShareIdRouteImport } from './routes/share/$id'
import { Route as AuthenticatedUsageRouteImport } from './routes/_authenticated/usage'
import { Route as AuthenticatedTopologyRouteImport } from './routes/_authenticated/topology'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedRunsRouteImport } from './routes/_authenticated/runs'
import { Route as AuthenticatedRetrieverRouteImport } from './routes/_authenticated/retriever'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedRemediationRouteImport } from './routes/_authenticated/remediation'
import { Route as AuthenticatedReliabilityRouteImport } from './routes/_authenticated/reliability'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated/prompts'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated/policies'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedOrgRouteImport } from './routes/_authenticated/org'
import { Route as AuthenticatedOptimizerRouteImport } from './routes/_authenticated/optimizer'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedObservabilityRouteImport } from './routes/_authenticated/observability'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedMcpRouteImport } from './routes/_authenticated/mcp'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedHarnessRouteImport } from './routes/_authenticated/harness'
import { Route as AuthenticatedGovernanceRouteImport } from './routes/_authenticated/governance'
import { Route as AuthenticatedExperimentsRouteImport } from './routes/_authenticated/experiments'
import { Route as AuthenticatedEvaluationsRouteImport } from './routes/_authenticated/evaluations'
import { Route as AuthenticatedEnterpriseAuthRouteImport } from './routes/_authenticated/enterprise-auth'
import { Route as AuthenticatedEnforcementRouteImport } from './routes/_authenticated/enforcement'
import { Route as AuthenticatedDeploymentsRouteImport } from './routes/_authenticated/deployments'
import { Route as AuthenticatedDatasetsRouteImport } from './routes/_authenticated/datasets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContextRouteImport } from './routes/_authenticated/context'
import { Route as AuthenticatedBudgetsRouteImport } from './routes/_authenticated/budgets'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as ApiPublicTriggersTokenRouteImport } from './routes/api/public/triggers/$token'
import { Route as ApiPublicScimV2RouteImport } from './routes/api/public/scim/v2'
import { Route as ApiPublicSchedulerTickRouteImport } from './routes/api/public/scheduler/tick'
import { Route as ApiPublicScimV2UsersRouteImport } from './routes/api/public/scim/v2/Users'
import { Route as ApiPublicScimV2UsersIdRouteImport } from './routes/api/public/scim/v2/Users/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsageRoute = AuthenticatedUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopologyRoute = AuthenticatedTopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRunsRoute = AuthenticatedRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetrieverRoute = AuthenticatedRetrieverRouteImport.update({
  id: '/retriever',
  path: '/retriever',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemediationRoute =
  AuthenticatedRemediationRouteImport.update({
    id: '/remediation',
    path: '/remediation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReliabilityRoute =
  AuthenticatedReliabilityRouteImport.update({
    id: '/reliability',
    path: '/reliability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgRoute = AuthenticatedOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOptimizerRoute = AuthenticatedOptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObservabilityRoute =
  AuthenticatedObservabilityRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMcpRoute = AuthenticatedMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHarnessRoute = AuthenticatedHarnessRouteImport.update({
  id: '/harness',
  path: '/harness',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovernanceRoute = AuthenticatedGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperimentsRoute =
  AuthenticatedExperimentsRouteImport.update({
    id: '/experiments',
    path: '/experiments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvaluationsRoute =
  AuthenticatedEvaluationsRouteImport.update({
    id: '/evaluations',
    path: '/evaluations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnterpriseAuthRoute =
  AuthenticatedEnterpriseAuthRouteImport.update({
    id: '/enterprise-auth',
    path: '/enterprise-auth',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnforcementRoute =
  AuthenticatedEnforcementRouteImport.update({
    id: '/enforcement',
    path: '/enforcement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeploymentsRoute =
  AuthenticatedDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatasetsRoute = AuthenticatedDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContextRoute = AuthenticatedContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetsRoute = AuthenticatedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicTriggersTokenRoute = ApiPublicTriggersTokenRouteImport.update({
  id: '/api/public/triggers/$token',
  path: '/api/public/triggers/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScimV2Route = ApiPublicScimV2RouteImport.update({
  id: '/api/public/scim/v2',
  path: '/api/public/scim/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSchedulerTickRoute = ApiPublicSchedulerTickRouteImport.update({
  id: '/api/public/scheduler/tick',
  path: '/api/public/scheduler/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScimV2UsersRoute = ApiPublicScimV2UsersRouteImport.update({
  id: '/Users',
  path: '/Users',
  getParentRoute: () => ApiPublicScimV2Route,
} as any)
const ApiPublicScimV2UsersIdRoute = ApiPublicScimV2UsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicScimV2UsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/context': typeof AuthenticatedContextRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/deployments': typeof AuthenticatedDeploymentsRoute
  '/enforcement': typeof AuthenticatedEnforcementRoute
  '/enterprise-auth': typeof AuthenticatedEnterpriseAuthRoute
  '/evaluations': typeof AuthenticatedEvaluationsRoute
  '/experiments': typeof AuthenticatedExperimentsRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/harness': typeof AuthenticatedHarnessRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/mcp': typeof AuthenticatedMcpRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/models': typeof AuthenticatedModelsRoute
  '/observability': typeof AuthenticatedObservabilityRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/optimizer': typeof AuthenticatedOptimizerRoute
  '/org': typeof AuthenticatedOrgRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/reliability': typeof AuthenticatedReliabilityRoute
  '/remediation': typeof AuthenticatedRemediationRoute
  '/research': typeof AuthenticatedResearchRoute
  '/retriever': typeof AuthenticatedRetrieverRoute
  '/runs': typeof AuthenticatedRunsRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/topology': typeof AuthenticatedTopologyRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/share/$id': typeof ShareIdRoute
  '/api/public/scheduler/tick': typeof ApiPublicSchedulerTickRoute
  '/api/public/scim/v2': typeof ApiPublicScimV2RouteWithChildren
  '/api/public/triggers/$token': typeof ApiPublicTriggersTokenRoute
  '/api/public/scim/v2/Users': typeof ApiPublicScimV2UsersRouteWithChildren
  '/api/public/scim/v2/Users/$id': typeof ApiPublicScimV2UsersIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/context': typeof AuthenticatedContextRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/deployments': typeof AuthenticatedDeploymentsRoute
  '/enforcement': typeof AuthenticatedEnforcementRoute
  '/enterprise-auth': typeof AuthenticatedEnterpriseAuthRoute
  '/evaluations': typeof AuthenticatedEvaluationsRoute
  '/experiments': typeof AuthenticatedExperimentsRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/harness': typeof AuthenticatedHarnessRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/mcp': typeof AuthenticatedMcpRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/models': typeof AuthenticatedModelsRoute
  '/observability': typeof AuthenticatedObservabilityRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/optimizer': typeof AuthenticatedOptimizerRoute
  '/org': typeof AuthenticatedOrgRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/policies': typeof AuthenticatedPoliciesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/reliability': typeof AuthenticatedReliabilityRoute
  '/remediation': typeof AuthenticatedRemediationRoute
  '/research': typeof AuthenticatedResearchRoute
  '/retriever': typeof AuthenticatedRetrieverRoute
  '/runs': typeof AuthenticatedRunsRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/topology': typeof AuthenticatedTopologyRoute
  '/usage': typeof AuthenticatedUsageRoute
  '/share/$id': typeof ShareIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/scheduler/tick': typeof ApiPublicSchedulerTickRoute
  '/api/public/scim/v2': typeof ApiPublicScimV2RouteWithChildren
  '/api/public/triggers/$token': typeof ApiPublicTriggersTokenRoute
  '/api/public/scim/v2/Users': typeof ApiPublicScimV2UsersRouteWithChildren
  '/api/public/scim/v2/Users/$id': typeof ApiPublicScimV2UsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/budgets': typeof AuthenticatedBudgetsRoute
  '/_authenticated/context': typeof AuthenticatedContextRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/datasets': typeof AuthenticatedDatasetsRoute
  '/_authenticated/deployments': typeof AuthenticatedDeploymentsRoute
  '/_authenticated/enforcement': typeof AuthenticatedEnforcementRoute
  '/_authenticated/enterprise-auth': typeof AuthenticatedEnterpriseAuthRoute
  '/_authenticated/evaluations': typeof AuthenticatedEvaluationsRoute
  '/_authenticated/experiments': typeof AuthenticatedExperimentsRoute
  '/_authenticated/governance': typeof AuthenticatedGovernanceRoute
  '/_authenticated/harness': typeof AuthenticatedHarnessRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/mcp': typeof AuthenticatedMcpRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/observability': typeof AuthenticatedObservabilityRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/optimizer': typeof AuthenticatedOptimizerRoute
  '/_authenticated/org': typeof AuthenticatedOrgRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/policies': typeof AuthenticatedPoliciesRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/reliability': typeof AuthenticatedReliabilityRoute
  '/_authenticated/remediation': typeof AuthenticatedRemediationRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/retriever': typeof AuthenticatedRetrieverRoute
  '/_authenticated/runs': typeof AuthenticatedRunsRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/topology': typeof AuthenticatedTopologyRoute
  '/_authenticated/usage': typeof AuthenticatedUsageRoute
  '/share/$id': typeof ShareIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/scheduler/tick': typeof ApiPublicSchedulerTickRoute
  '/api/public/scim/v2': typeof ApiPublicScimV2RouteWithChildren
  '/api/public/triggers/$token': typeof ApiPublicTriggersTokenRoute
  '/api/public/scim/v2/Users': typeof ApiPublicScimV2UsersRouteWithChildren
  '/api/public/scim/v2/Users/$id': typeof ApiPublicScimV2UsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/agents'
    | '/alerts'
    | '/api-keys'
    | '/audit'
    | '/budgets'
    | '/context'
    | '/dashboard'
    | '/datasets'
    | '/deployments'
    | '/enforcement'
    | '/enterprise-auth'
    | '/evaluations'
    | '/experiments'
    | '/governance'
    | '/harness'
    | '/integrations'
    | '/library'
    | '/mcp'
    | '/memory'
    | '/models'
    | '/observability'
    | '/onboarding'
    | '/optimizer'
    | '/org'
    | '/planner'
    | '/policies'
    | '/projects'
    | '/prompts'
    | '/reliability'
    | '/remediation'
    | '/research'
    | '/retriever'
    | '/runs'
    | '/schedules'
    | '/settings'
    | '/tools'
    | '/topology'
    | '/usage'
    | '/share/$id'
    | '/api/public/scheduler/tick'
    | '/api/public/scim/v2'
    | '/api/public/triggers/$token'
    | '/api/public/scim/v2/Users'
    | '/api/public/scim/v2/Users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/agents'
    | '/alerts'
    | '/api-keys'
    | '/audit'
    | '/budgets'
    | '/context'
    | '/dashboard'
    | '/datasets'
    | '/deployments'
    | '/enforcement'
    | '/enterprise-auth'
    | '/evaluations'
    | '/experiments'
    | '/governance'
    | '/harness'
    | '/integrations'
    | '/library'
    | '/mcp'
    | '/memory'
    | '/models'
    | '/observability'
    | '/onboarding'
    | '/optimizer'
    | '/org'
    | '/planner'
    | '/policies'
    | '/projects'
    | '/prompts'
    | '/reliability'
    | '/remediation'
    | '/research'
    | '/retriever'
    | '/runs'
    | '/schedules'
    | '/settings'
    | '/tools'
    | '/topology'
    | '/usage'
    | '/share/$id'
    | '/'
    | '/api/public/scheduler/tick'
    | '/api/public/scim/v2'
    | '/api/public/triggers/$token'
    | '/api/public/scim/v2/Users'
    | '/api/public/scim/v2/Users/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/agents'
    | '/_authenticated/alerts'
    | '/_authenticated/api-keys'
    | '/_authenticated/audit'
    | '/_authenticated/budgets'
    | '/_authenticated/context'
    | '/_authenticated/dashboard'
    | '/_authenticated/datasets'
    | '/_authenticated/deployments'
    | '/_authenticated/enforcement'
    | '/_authenticated/enterprise-auth'
    | '/_authenticated/evaluations'
    | '/_authenticated/experiments'
    | '/_authenticated/governance'
    | '/_authenticated/harness'
    | '/_authenticated/integrations'
    | '/_authenticated/library'
    | '/_authenticated/mcp'
    | '/_authenticated/memory'
    | '/_authenticated/models'
    | '/_authenticated/observability'
    | '/_authenticated/onboarding'
    | '/_authenticated/optimizer'
    | '/_authenticated/org'
    | '/_authenticated/planner'
    | '/_authenticated/policies'
    | '/_authenticated/projects'
    | '/_authenticated/prompts'
    | '/_authenticated/reliability'
    | '/_authenticated/remediation'
    | '/_authenticated/research'
    | '/_authenticated/retriever'
    | '/_authenticated/runs'
    | '/_authenticated/schedules'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/_authenticated/topology'
    | '/_authenticated/usage'
    | '/share/$id'
    | '/_authenticated/'
    | '/api/public/scheduler/tick'
    | '/api/public/scim/v2'
    | '/api/public/triggers/$token'
    | '/api/public/scim/v2/Users'
    | '/api/public/scim/v2/Users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShareIdRoute: typeof ShareIdRoute
  ApiPublicSchedulerTickRoute: typeof ApiPublicSchedulerTickRoute
  ApiPublicScimV2Route: typeof ApiPublicScimV2RouteWithChildren
  ApiPublicTriggersTokenRoute: typeof ApiPublicTriggersTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usage': {
      id: '/_authenticated/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topology': {
      id: '/_authenticated/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof AuthenticatedTopologyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runs': {
      id: '/_authenticated/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AuthenticatedRunsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retriever': {
      id: '/_authenticated/retriever'
      path: '/retriever'
      fullPath: '/retriever'
      preLoaderRoute: typeof AuthenticatedRetrieverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remediation': {
      id: '/_authenticated/remediation'
      path: '/remediation'
      fullPath: '/remediation'
      preLoaderRoute: typeof AuthenticatedRemediationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reliability': {
      id: '/_authenticated/reliability'
      path: '/reliability'
      fullPath: '/reliability'
      preLoaderRoute: typeof AuthenticatedReliabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org': {
      id: '/_authenticated/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AuthenticatedOrgRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/optimizer': {
      id: '/_authenticated/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof AuthenticatedOptimizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/observability': {
      id: '/_authenticated/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof AuthenticatedObservabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mcp': {
      id: '/_authenticated/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof AuthenticatedMcpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/harness': {
      id: '/_authenticated/harness'
      path: '/harness'
      fullPath: '/harness'
      preLoaderRoute: typeof AuthenticatedHarnessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance': {
      id: '/_authenticated/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthenticatedGovernanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiments': {
      id: '/_authenticated/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof AuthenticatedExperimentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluations': {
      id: '/_authenticated/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof AuthenticatedEvaluationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enterprise-auth': {
      id: '/_authenticated/enterprise-auth'
      path: '/enterprise-auth'
      fullPath: '/enterprise-auth'
      preLoaderRoute: typeof AuthenticatedEnterpriseAuthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enforcement': {
      id: '/_authenticated/enforcement'
      path: '/enforcement'
      fullPath: '/enforcement'
      preLoaderRoute: typeof AuthenticatedEnforcementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deployments': {
      id: '/_authenticated/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof AuthenticatedDeploymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets': {
      id: '/_authenticated/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AuthenticatedDatasetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/context': {
      id: '/_authenticated/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof AuthenticatedContextRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budgets': {
      id: '/_authenticated/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthenticatedBudgetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/triggers/$token': {
      id: '/api/public/triggers/$token'
      path: '/api/public/triggers/$token'
      fullPath: '/api/public/triggers/$token'
      preLoaderRoute: typeof ApiPublicTriggersTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scim/v2': {
      id: '/api/public/scim/v2'
      path: '/api/public/scim/v2'
      fullPath: '/api/public/scim/v2'
      preLoaderRoute: typeof ApiPublicScimV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scheduler/tick': {
      id: '/api/public/scheduler/tick'
      path: '/api/public/scheduler/tick'
      fullPath: '/api/public/scheduler/tick'
      preLoaderRoute: typeof ApiPublicSchedulerTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scim/v2/Users': {
      id: '/api/public/scim/v2/Users'
      path: '/Users'
      fullPath: '/api/public/scim/v2/Users'
      preLoaderRoute: typeof ApiPublicScimV2UsersRouteImport
      parentRoute: typeof ApiPublicScimV2Route
    }
    '/api/public/scim/v2/Users/$id': {
      id: '/api/public/scim/v2/Users/$id'
      path: '/$id'
      fullPath: '/api/public/scim/v2/Users/$id'
      preLoaderRoute: typeof ApiPublicScimV2UsersIdRouteImport
      parentRoute: typeof ApiPublicScimV2UsersRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBudgetsRoute: typeof AuthenticatedBudgetsRoute
  AuthenticatedContextRoute: typeof AuthenticatedContextRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatasetsRoute: typeof AuthenticatedDatasetsRoute
  AuthenticatedDeploymentsRoute: typeof AuthenticatedDeploymentsRoute
  AuthenticatedEnforcementRoute: typeof AuthenticatedEnforcementRoute
  AuthenticatedEnterpriseAuthRoute: typeof AuthenticatedEnterpriseAuthRoute
  AuthenticatedEvaluationsRoute: typeof AuthenticatedEvaluationsRoute
  AuthenticatedExperimentsRoute: typeof AuthenticatedExperimentsRoute
  AuthenticatedGovernanceRoute: typeof AuthenticatedGovernanceRoute
  AuthenticatedHarnessRoute: typeof AuthenticatedHarnessRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMcpRoute: typeof AuthenticatedMcpRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedObservabilityRoute: typeof AuthenticatedObservabilityRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOptimizerRoute: typeof AuthenticatedOptimizerRoute
  AuthenticatedOrgRoute: typeof AuthenticatedOrgRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedReliabilityRoute: typeof AuthenticatedReliabilityRoute
  AuthenticatedRemediationRoute: typeof AuthenticatedRemediationRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedRetrieverRoute: typeof AuthenticatedRetrieverRoute
  AuthenticatedRunsRoute: typeof AuthenticatedRunsRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedTopologyRoute: typeof AuthenticatedTopologyRoute
  AuthenticatedUsageRoute: typeof AuthenticatedUsageRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBudgetsRoute: AuthenticatedBudgetsRoute,
  AuthenticatedContextRoute: AuthenticatedContextRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatasetsRoute: AuthenticatedDatasetsRoute,
  AuthenticatedDeploymentsRoute: AuthenticatedDeploymentsRoute,
  AuthenticatedEnforcementRoute: AuthenticatedEnforcementRoute,
  AuthenticatedEnterpriseAuthRoute: AuthenticatedEnterpriseAuthRoute,
  AuthenticatedEvaluationsRoute: AuthenticatedEvaluationsRoute,
  AuthenticatedExperimentsRoute: AuthenticatedExperimentsRoute,
  AuthenticatedGovernanceRoute: AuthenticatedGovernanceRoute,
  AuthenticatedHarnessRoute: AuthenticatedHarnessRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMcpRoute: AuthenticatedMcpRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedObservabilityRoute: AuthenticatedObservabilityRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOptimizerRoute: AuthenticatedOptimizerRoute,
  AuthenticatedOrgRoute: AuthenticatedOrgRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedReliabilityRoute: AuthenticatedReliabilityRoute,
  AuthenticatedRemediationRoute: AuthenticatedRemediationRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedRetrieverRoute: AuthenticatedRetrieverRoute,
  AuthenticatedRunsRoute: AuthenticatedRunsRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedTopologyRoute: AuthenticatedTopologyRoute,
  AuthenticatedUsageRoute: AuthenticatedUsageRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicScimV2UsersRouteChildren {
  ApiPublicScimV2UsersIdRoute: typeof ApiPublicScimV2UsersIdRoute
}

const ApiPublicScimV2UsersRouteChildren: ApiPublicScimV2UsersRouteChildren = {
  ApiPublicScimV2UsersIdRoute: ApiPublicScimV2UsersIdRoute,
}

const ApiPublicScimV2UsersRouteWithChildren =
  ApiPublicScimV2UsersRoute._addFileChildren(ApiPublicScimV2UsersRouteChildren)

interface ApiPublicScimV2RouteChildren {
  ApiPublicScimV2UsersRoute: typeof ApiPublicScimV2UsersRouteWithChildren
}

const ApiPublicScimV2RouteChildren: ApiPublicScimV2RouteChildren = {
  ApiPublicScimV2UsersRoute: ApiPublicScimV2UsersRouteWithChildren,
}

const ApiPublicScimV2RouteWithChildren = ApiPublicScimV2Route._addFileChildren(
  ApiPublicScimV2RouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShareIdRoute: ShareIdRoute,
  ApiPublicSchedulerTickRoute: ApiPublicSchedulerTickRoute,
  ApiPublicScimV2Route: ApiPublicScimV2RouteWithChildren,
  ApiPublicTriggersTokenRoute: ApiPublicTriggersTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
